/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-01 at 04:48:33 UTC 
 * Modify at your own risk.
 */

package com.testappengine.deviceinfoendpoint.model;

/**
 * Model definition for DeviceInfo.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the deviceinfoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DeviceInfo extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comDownToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comDownToAdd2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comJunkToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comJunkToAdd2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comPromToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comUpToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comUpToAdd2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> commentsDownvoted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> commentsJunked;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> commentsPromoted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> commentsUpvoted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deviceInformation;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deviceRegistrationID;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Boolean> downvotedIdeas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer downvotedIdeasToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Boolean> junkedIdeas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer junkedIdeasToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Boolean> promotedIdeas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer promotedIdeasToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long timestamp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Boolean> upvotedIdeas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer upvotedIdeasToAdd;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComDownToAdd() {
    return comDownToAdd;
  }

  /**
   * @param comDownToAdd comDownToAdd or {@code null} for none
   */
  public DeviceInfo setComDownToAdd(java.lang.Integer comDownToAdd) {
    this.comDownToAdd = comDownToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComDownToAdd2() {
    return comDownToAdd2;
  }

  /**
   * @param comDownToAdd2 comDownToAdd2 or {@code null} for none
   */
  public DeviceInfo setComDownToAdd2(java.lang.Integer comDownToAdd2) {
    this.comDownToAdd2 = comDownToAdd2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComJunkToAdd() {
    return comJunkToAdd;
  }

  /**
   * @param comJunkToAdd comJunkToAdd or {@code null} for none
   */
  public DeviceInfo setComJunkToAdd(java.lang.Integer comJunkToAdd) {
    this.comJunkToAdd = comJunkToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComJunkToAdd2() {
    return comJunkToAdd2;
  }

  /**
   * @param comJunkToAdd2 comJunkToAdd2 or {@code null} for none
   */
  public DeviceInfo setComJunkToAdd2(java.lang.Integer comJunkToAdd2) {
    this.comJunkToAdd2 = comJunkToAdd2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComPromToAdd() {
    return comPromToAdd;
  }

  /**
   * @param comPromToAdd comPromToAdd or {@code null} for none
   */
  public DeviceInfo setComPromToAdd(java.lang.Integer comPromToAdd) {
    this.comPromToAdd = comPromToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComUpToAdd() {
    return comUpToAdd;
  }

  /**
   * @param comUpToAdd comUpToAdd or {@code null} for none
   */
  public DeviceInfo setComUpToAdd(java.lang.Integer comUpToAdd) {
    this.comUpToAdd = comUpToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComUpToAdd2() {
    return comUpToAdd2;
  }

  /**
   * @param comUpToAdd2 comUpToAdd2 or {@code null} for none
   */
  public DeviceInfo setComUpToAdd2(java.lang.Integer comUpToAdd2) {
    this.comUpToAdd2 = comUpToAdd2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCommentsDownvoted() {
    return commentsDownvoted;
  }

  /**
   * @param commentsDownvoted commentsDownvoted or {@code null} for none
   */
  public DeviceInfo setCommentsDownvoted(java.util.List<java.lang.String> commentsDownvoted) {
    this.commentsDownvoted = commentsDownvoted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCommentsJunked() {
    return commentsJunked;
  }

  /**
   * @param commentsJunked commentsJunked or {@code null} for none
   */
  public DeviceInfo setCommentsJunked(java.util.List<java.lang.String> commentsJunked) {
    this.commentsJunked = commentsJunked;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCommentsPromoted() {
    return commentsPromoted;
  }

  /**
   * @param commentsPromoted commentsPromoted or {@code null} for none
   */
  public DeviceInfo setCommentsPromoted(java.util.List<java.lang.String> commentsPromoted) {
    this.commentsPromoted = commentsPromoted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCommentsUpvoted() {
    return commentsUpvoted;
  }

  /**
   * @param commentsUpvoted commentsUpvoted or {@code null} for none
   */
  public DeviceInfo setCommentsUpvoted(java.util.List<java.lang.String> commentsUpvoted) {
    this.commentsUpvoted = commentsUpvoted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceInformation() {
    return deviceInformation;
  }

  /**
   * @param deviceInformation deviceInformation or {@code null} for none
   */
  public DeviceInfo setDeviceInformation(java.lang.String deviceInformation) {
    this.deviceInformation = deviceInformation;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeviceRegistrationID() {
    return deviceRegistrationID;
  }

  /**
   * @param deviceRegistrationID deviceRegistrationID or {@code null} for none
   */
  public DeviceInfo setDeviceRegistrationID(java.lang.String deviceRegistrationID) {
    this.deviceRegistrationID = deviceRegistrationID;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Boolean> getDownvotedIdeas() {
    return downvotedIdeas;
  }

  /**
   * @param downvotedIdeas downvotedIdeas or {@code null} for none
   */
  public DeviceInfo setDownvotedIdeas(java.util.List<java.lang.Boolean> downvotedIdeas) {
    this.downvotedIdeas = downvotedIdeas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDownvotedIdeasToAdd() {
    return downvotedIdeasToAdd;
  }

  /**
   * @param downvotedIdeasToAdd downvotedIdeasToAdd or {@code null} for none
   */
  public DeviceInfo setDownvotedIdeasToAdd(java.lang.Integer downvotedIdeasToAdd) {
    this.downvotedIdeasToAdd = downvotedIdeasToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Boolean> getJunkedIdeas() {
    return junkedIdeas;
  }

  /**
   * @param junkedIdeas junkedIdeas or {@code null} for none
   */
  public DeviceInfo setJunkedIdeas(java.util.List<java.lang.Boolean> junkedIdeas) {
    this.junkedIdeas = junkedIdeas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getJunkedIdeasToAdd() {
    return junkedIdeasToAdd;
  }

  /**
   * @param junkedIdeasToAdd junkedIdeasToAdd or {@code null} for none
   */
  public DeviceInfo setJunkedIdeasToAdd(java.lang.Integer junkedIdeasToAdd) {
    this.junkedIdeasToAdd = junkedIdeasToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Boolean> getPromotedIdeas() {
    return promotedIdeas;
  }

  /**
   * @param promotedIdeas promotedIdeas or {@code null} for none
   */
  public DeviceInfo setPromotedIdeas(java.util.List<java.lang.Boolean> promotedIdeas) {
    this.promotedIdeas = promotedIdeas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPromotedIdeasToAdd() {
    return promotedIdeasToAdd;
  }

  /**
   * @param promotedIdeasToAdd promotedIdeasToAdd or {@code null} for none
   */
  public DeviceInfo setPromotedIdeasToAdd(java.lang.Integer promotedIdeasToAdd) {
    this.promotedIdeasToAdd = promotedIdeasToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * @param timestamp timestamp or {@code null} for none
   */
  public DeviceInfo setTimestamp(java.lang.Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Boolean> getUpvotedIdeas() {
    return upvotedIdeas;
  }

  /**
   * @param upvotedIdeas upvotedIdeas or {@code null} for none
   */
  public DeviceInfo setUpvotedIdeas(java.util.List<java.lang.Boolean> upvotedIdeas) {
    this.upvotedIdeas = upvotedIdeas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getUpvotedIdeasToAdd() {
    return upvotedIdeasToAdd;
  }

  /**
   * @param upvotedIdeasToAdd upvotedIdeasToAdd or {@code null} for none
   */
  public DeviceInfo setUpvotedIdeasToAdd(java.lang.Integer upvotedIdeasToAdd) {
    this.upvotedIdeasToAdd = upvotedIdeasToAdd;
    return this;
  }

  @Override
  public DeviceInfo set(String fieldName, Object value) {
    return (DeviceInfo) super.set(fieldName, value);
  }

  @Override
  public DeviceInfo clone() {
    return (DeviceInfo) super.clone();
  }

}
