/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-01 at 04:48:36 UTC 
 * Modify at your own risk.
 */

package com.testappengine.userendpoint.model;

/**
 * Model definition for User.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the userendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class User extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comDownToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comDownToAdd2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comJunkToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comJunkToAdd2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comPromToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comUpToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer comUpToAdd2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> commentsDownvoted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> commentsJunked;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Boolean> commentsPromoted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> commentsUpvoted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Boolean> downvotedIdeas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer downvotedIdeasToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Boolean> junkedIdeas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer junkedIdeasToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String password;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer promotions;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer promotionsToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime registerDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.Boolean> upvotedIdeas;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer upvotedIdeasToAdd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String username;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComDownToAdd() {
    return comDownToAdd;
  }

  /**
   * @param comDownToAdd comDownToAdd or {@code null} for none
   */
  public User setComDownToAdd(java.lang.Integer comDownToAdd) {
    this.comDownToAdd = comDownToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComDownToAdd2() {
    return comDownToAdd2;
  }

  /**
   * @param comDownToAdd2 comDownToAdd2 or {@code null} for none
   */
  public User setComDownToAdd2(java.lang.Integer comDownToAdd2) {
    this.comDownToAdd2 = comDownToAdd2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComJunkToAdd() {
    return comJunkToAdd;
  }

  /**
   * @param comJunkToAdd comJunkToAdd or {@code null} for none
   */
  public User setComJunkToAdd(java.lang.Integer comJunkToAdd) {
    this.comJunkToAdd = comJunkToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComJunkToAdd2() {
    return comJunkToAdd2;
  }

  /**
   * @param comJunkToAdd2 comJunkToAdd2 or {@code null} for none
   */
  public User setComJunkToAdd2(java.lang.Integer comJunkToAdd2) {
    this.comJunkToAdd2 = comJunkToAdd2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComPromToAdd() {
    return comPromToAdd;
  }

  /**
   * @param comPromToAdd comPromToAdd or {@code null} for none
   */
  public User setComPromToAdd(java.lang.Integer comPromToAdd) {
    this.comPromToAdd = comPromToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComUpToAdd() {
    return comUpToAdd;
  }

  /**
   * @param comUpToAdd comUpToAdd or {@code null} for none
   */
  public User setComUpToAdd(java.lang.Integer comUpToAdd) {
    this.comUpToAdd = comUpToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getComUpToAdd2() {
    return comUpToAdd2;
  }

  /**
   * @param comUpToAdd2 comUpToAdd2 or {@code null} for none
   */
  public User setComUpToAdd2(java.lang.Integer comUpToAdd2) {
    this.comUpToAdd2 = comUpToAdd2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCommentsDownvoted() {
    return commentsDownvoted;
  }

  /**
   * @param commentsDownvoted commentsDownvoted or {@code null} for none
   */
  public User setCommentsDownvoted(java.util.List<java.lang.String> commentsDownvoted) {
    this.commentsDownvoted = commentsDownvoted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCommentsJunked() {
    return commentsJunked;
  }

  /**
   * @param commentsJunked commentsJunked or {@code null} for none
   */
  public User setCommentsJunked(java.util.List<java.lang.String> commentsJunked) {
    this.commentsJunked = commentsJunked;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Boolean> getCommentsPromoted() {
    return commentsPromoted;
  }

  /**
   * @param commentsPromoted commentsPromoted or {@code null} for none
   */
  public User setCommentsPromoted(java.util.List<java.lang.Boolean> commentsPromoted) {
    this.commentsPromoted = commentsPromoted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCommentsUpvoted() {
    return commentsUpvoted;
  }

  /**
   * @param commentsUpvoted commentsUpvoted or {@code null} for none
   */
  public User setCommentsUpvoted(java.util.List<java.lang.String> commentsUpvoted) {
    this.commentsUpvoted = commentsUpvoted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Boolean> getDownvotedIdeas() {
    return downvotedIdeas;
  }

  /**
   * @param downvotedIdeas downvotedIdeas or {@code null} for none
   */
  public User setDownvotedIdeas(java.util.List<java.lang.Boolean> downvotedIdeas) {
    this.downvotedIdeas = downvotedIdeas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDownvotedIdeasToAdd() {
    return downvotedIdeasToAdd;
  }

  /**
   * @param downvotedIdeasToAdd downvotedIdeasToAdd or {@code null} for none
   */
  public User setDownvotedIdeasToAdd(java.lang.Integer downvotedIdeasToAdd) {
    this.downvotedIdeasToAdd = downvotedIdeasToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public User setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Boolean> getJunkedIdeas() {
    return junkedIdeas;
  }

  /**
   * @param junkedIdeas junkedIdeas or {@code null} for none
   */
  public User setJunkedIdeas(java.util.List<java.lang.Boolean> junkedIdeas) {
    this.junkedIdeas = junkedIdeas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getJunkedIdeasToAdd() {
    return junkedIdeasToAdd;
  }

  /**
   * @param junkedIdeasToAdd junkedIdeasToAdd or {@code null} for none
   */
  public User setJunkedIdeasToAdd(java.lang.Integer junkedIdeasToAdd) {
    this.junkedIdeasToAdd = junkedIdeasToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public User setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPassword() {
    return password;
  }

  /**
   * @param password password or {@code null} for none
   */
  public User setPassword(java.lang.String password) {
    this.password = password;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPromotions() {
    return promotions;
  }

  /**
   * @param promotions promotions or {@code null} for none
   */
  public User setPromotions(java.lang.Integer promotions) {
    this.promotions = promotions;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getPromotionsToAdd() {
    return promotionsToAdd;
  }

  /**
   * @param promotionsToAdd promotionsToAdd or {@code null} for none
   */
  public User setPromotionsToAdd(java.lang.Integer promotionsToAdd) {
    this.promotionsToAdd = promotionsToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getRegisterDate() {
    return registerDate;
  }

  /**
   * @param registerDate registerDate or {@code null} for none
   */
  public User setRegisterDate(com.google.api.client.util.DateTime registerDate) {
    this.registerDate = registerDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.Boolean> getUpvotedIdeas() {
    return upvotedIdeas;
  }

  /**
   * @param upvotedIdeas upvotedIdeas or {@code null} for none
   */
  public User setUpvotedIdeas(java.util.List<java.lang.Boolean> upvotedIdeas) {
    this.upvotedIdeas = upvotedIdeas;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getUpvotedIdeasToAdd() {
    return upvotedIdeasToAdd;
  }

  /**
   * @param upvotedIdeasToAdd upvotedIdeasToAdd or {@code null} for none
   */
  public User setUpvotedIdeasToAdd(java.lang.Integer upvotedIdeasToAdd) {
    this.upvotedIdeasToAdd = upvotedIdeasToAdd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUsername() {
    return username;
  }

  /**
   * @param username username or {@code null} for none
   */
  public User setUsername(java.lang.String username) {
    this.username = username;
    return this;
  }

  @Override
  public User set(String fieldName, Object value) {
    return (User) super.set(fieldName, value);
  }

  @Override
  public User clone() {
    return (User) super.clone();
  }

}
